# Generated by Django 3.2.25 on 2026-01-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_manager', '0002_employee_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
